### ISSUE TITLE
fails when dir not exist?

### ISSUE THREAD

**Issue by fliiiix** [Binaergewitter/chapter-marker#11]
Traceback (most recent call last):
  File "/home/l33tname/git/bgt/chapter-marker/chapter_marker/tray.py", line 273, in save
    self.markers.persist()
  File "/home/l33tname/git/bgt/chapter-marker/chapter_marker/tray.py", line 183, in persist
    with open(dbpath, "wb+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/l33tname/.local/share/chapter-marker/bgt288.db'

**Comment by makefu** [comment]
`os.makedirs(dirname(self.location,exist_ok=true)` vor dem write in self.persist
